services:
  web:
    build:
      context: .
    working_dir: /app/library
    command: >
      sh -c "python manage.py migrate &&
             coverage run -m pytest &&
             coverage html"
    volumes:
      - .:/app
      - ./library/htmlcov:/app/library/htmlcov
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
